python: can't open file 'per_high_low.': [Errno 2] No such file or directory
9138
Successfully processed A
Successfully processed AA
Successfully processed AAA
Successfully processed AAAU
Successfully processed AACG
Successfully processed AACQ
Failed to process AACQU: 'close'.
Failed to process AACQW: 'close'.
Successfully processed AADR
Successfully processed AAL
9138
Successfully processed A
Successfully processed AA
Successfully processed AAA
Successfully processed AAAU
Successfully processed AACG
Successfully processed AACQ
Failed to process AACQU: 'close'.
Failed to process AACQW: 'close'.
Successfully processed AADR
Successfully processed AAL
Traceback (most recent call last):
  File "per_high_low.py", line 158, in <module>
    main()
  File "per_high_low.py", line 155, in main
    save_daily_results(df_res)
  File "per_high_low.py", line 137, in save_daily_results
    fig.savefig(f"{BUCKET_DIR}/per_high_low_latest.png")
  File "/usr/local/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "/usr/local/lib/python3.8/site-packages/matplotlib/image.py", line 1605, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2155, in save
    fp.close()
OSError: [Errno 5] Input/output error
9138
Successfully processed A
Successfully processed AA
Successfully processed AAA
Successfully processed AAAU
Successfully processed AACG
Successfully processed AACQ
Failed to process AACQU: 'close'.
Failed to process AACQW: 'close'.
Successfully processed AADR
Successfully processed AAL
